# Default values for stable-diffusion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # repository: registry.dso.interieur.rie.gouv.fr/dockerhub/jaubertaot/sd
  repository: registry.dso.interieur.rie.gouv.fr/dockerhub/amithkk/stable-diffusion
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# Stable Diffusion and optional companion models. Change these out if you'd like
models:
  sd14: http://minio-gpu.app1hp.d436.dev.forge.minint.fr/api/v1/download-shared-object/aHR0cDovL2xvY2FsaG9zdDo5MDAwL2FwcC92MS01LXBydW5lZC1lbWFvbmx5LmNrcHQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1YR0k4NzZIWk9UTlZPVURFTFhFTSUyRjIwMjUwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyM1QxMjM1MzNaJlgtQW16LUV4cGlyZXM9NDMyMDAmWC1BbXotU2VjdXJpdHktVG9rZW49ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhZMk5sYzNOTFpYa2lPaUpZUjBrNE56WklXazlVVGxaUFZVUkZURmhGVFNJc0ltVjRjQ0k2TVRjME9EQTBOalkwTUN3aWNHRnlaVzUwSWpvaVlXUnRhVzRpZlEuMGhOU3ZQdUxTMVp2S1NYVUpYaDZ4U0hKR2FxM294NlBKbHRUbjRBeUZwUFpIU2dTQUwxd3IxTTFEN2RIMEVsdVY1RDlsTjBQX2ZnX0p4RWh5dlV2WHcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnZlcnNpb25JZD1udWxsJlgtQW16LVNpZ25hdHVyZT1lMTMxMWIwMTFhOTU2MzJmYTg5NWJiZGY1MGJlZTU5ZjljYmExYmU1YTgxYzgxMzhiNGZjMDAyMjNiNGE5ZjYw
  gfpGan13: https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.3.pth
  realEsrGanx4p10: https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth
  realEsrGanx4Animep02: https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "sd"
cliFlags: "--extra-models-cpu --optimized-turbo"

persistence:
  annotations: {}
  ## If defined, storageClass: <storageClass>
  ## If set to "-", storageClass: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClass spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  accessMode: ReadWriteOnce
  size: 8Gi


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sd.demogpu.d436.dev.forge.minint.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 2
    memory: 4Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 2
    memory: 4Gi
    nvidia.com/gpu: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: 
  nvidia.com/gpu.present: "true"

tolerations: []

affinity: {}
